/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.bitadventurer.api.errors;

import com.bitadventurer.api.core.BitadventurerApiApiException;

public final class MethodNotAllowedError extends BitadventurerApiApiException {
    /**
     * The body of the response that triggered the exception.
     */
    private final Object body;

    public MethodNotAllowedError(Object body) {
        super("MethodNotAllowedError", 405, body);
        this.body = body;
    }

    /**
     * @return the body
     */
    @java.lang.Override
    public Object body() {
        return this.body;
    }
}
