/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.bitadventurer.api.core;

/**
 * This class serves as the base exception for all errors in the SDK.
 */
public class BitadventurerApiException extends RuntimeException {
    public BitadventurerApiException(String message) {
        super(message);
    }

    public BitadventurerApiException(String message, Exception e) {
        super(message, e);
    }
}
