/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.bitadventurer.api;

import com.bitadventurer.api.core.ClientOptions;
import com.bitadventurer.api.core.Environment;

public final class BitadventurerApiClientBuilder {
    private ClientOptions.Builder clientOptionsBuilder = ClientOptions.builder();

    private String token = null;

    private String apiKey = null;

    private Environment environment = Environment.DEFAULT;

    /**
     * Sets token
     */
    public BitadventurerApiClientBuilder token(String token) {
        this.token = token;
        return this;
    }

    /**
     * Sets apiKey
     */
    public BitadventurerApiClientBuilder apiKey(String apiKey) {
        this.apiKey = apiKey;
        return this;
    }

    public BitadventurerApiClientBuilder environment(Environment environment) {
        this.environment = environment;
        return this;
    }

    public BitadventurerApiClientBuilder url(String url) {
        this.environment = Environment.custom(url);
        return this;
    }

    public BitadventurerApiClient build() {
        this.clientOptionsBuilder.addHeader("Authorization", "Bearer " + this.token);
        if (apiKey == null) {
            throw new RuntimeException("Please provide apiKey");
        }
        this.clientOptionsBuilder.addHeader("api_key", this.apiKey);
        clientOptionsBuilder.environment(this.environment);
        return new BitadventurerApiClient(clientOptionsBuilder.build());
    }
}
