/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.bitadventurer.api;

import com.bitadventurer.api.core.ClientOptions;
import com.bitadventurer.api.core.Suppliers;
import com.bitadventurer.api.resources.pet.PetClient;
import com.bitadventurer.api.resources.store.StoreClient;
import com.bitadventurer.api.resources.user.UserClient;
import java.util.function.Supplier;

public class BitadventurerApiClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<PetClient> petClient;

    protected final Supplier<StoreClient> storeClient;

    protected final Supplier<UserClient> userClient;

    public BitadventurerApiClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.petClient = Suppliers.memoize(() -> new PetClient(clientOptions));
        this.storeClient = Suppliers.memoize(() -> new StoreClient(clientOptions));
        this.userClient = Suppliers.memoize(() -> new UserClient(clientOptions));
    }

    public PetClient pet() {
        return this.petClient.get();
    }

    public StoreClient store() {
        return this.storeClient.get();
    }

    public UserClient user() {
        return this.userClient.get();
    }

    public static BitadventurerApiClientBuilder builder() {
        return new BitadventurerApiClientBuilder();
    }
}
