/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.bitadventurer.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum OauthScope {
    WRITE_PETS("write:pets"),

    READ_PETS("read:pets");

    private final String value;

    OauthScope(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
